export const cities = [
  { label: 'Dhaka' },
  { label: 'Faridpur' },
  { label: 'Gazipur' },
  { label: 'Gopalganj' },
  { label: 'Jamalpur' },
  { label: 'Kishoreganj' },
  { label: 'Madaripur' },
  { label: 'Manikganj' },
  { label: 'Munshiganj' },
  { label: 'Mymensingh' },
  { label: 'Narayanganj' },
  { label: 'Narsingdi' },
  { label: 'Netrokona' },
  { label: 'Rajbari' },
  { label: 'Shariatpur' },
  { label: 'Sherpur' },
  { label: 'Tangail' },
  { label: 'Bogra' },
  { label: 'Joypurhat' },
  { label: 'Naogaon' },
  { label: 'Natore' },
  { label: 'Nawabganj' },
  { label: 'Pabna' },
  { label: 'Rajshahi' },
  { label: 'Sirajgonj' },
  { label: 'Dinajpur' },
  { label: 'Gaibandha' },
  { label: 'Kurigram' },
  { label: 'Lalmonirhat' },
  { label: 'Nilphamari' },
  { label: 'Panchagarh' },
  { label: 'Rangpur' },
  { label: 'Thakurgaon' },
  { label: 'Barguna' },
  { label: 'Barisal' },
  { label: 'Bhola' },
  { label: 'Jhalokati' },
  { label: 'Patuakhali' },
  { label: 'Pirojpur' },
  { label: 'Bandarban' },
  { label: 'Brahmanbaria' },
  { label: 'Chandpur' },
  { label: 'Chittagong' },
  { label: 'Comilla' },
  { label: 'Cox\'s Bazar' },
  { label: 'Feni' },
  { label: 'Khagrachari' },
  { label: 'Lakshmipur' },
  { label: 'Noakhali' },
  { label: 'Rangamati' },
  { label: 'Habiganj' },
  { label: 'Maulvibazar' },
  { label: 'Sunamganj' },
  { label: 'Sylhet' },
  { label: 'Bagerhat' },
  { label: 'Chuadanga' },
  { label: 'Jessore' },
  { label: 'Jhenaidah' },
  { label: 'Khulna' },
  { label: 'Kushtia' },
  { label: 'Magura' },
  { label: 'Meherpur' },
  { label: 'Narail' },
  { label: 'Satkhira' },
];

  export const bedrooms = [
    { label: "2" },
    { label: "3" },
    { label: "4" },
    { label: "5" },
    { label: "6" },
  ];
  export const roomsSize = [
    { label: "1200 square feet" },
    { label: "1500 square feet" },
    { label: "2000 square feet" },
    { label: "2500 square feet" },
    { label: "3000 square feet" },
  ];

  export const available = [
    { label: "Yes Available" },
    { label: "Not Available" },

  ];

  export const marks = [
    {
      value: 1000,
      label: "1k $",
    },
    {
      value: 1500,
      label: "1.5k $",
    },
    {
      value: 2000,
      label: "2k $",
    },
    {
      value: 2500,
      label: "2.5k $",
    },
  ];
  